---
- name: Copy the Node Exporter systemd service file
  template:
    src: node_exporter.service.j2
    dest: "{{ otus_node_exporter_service_dir }}/{{ otus_node_exporter_service_name }}.service"
    owner: root
    group: root
    mode: 0644
  register: __ansible_otus_node_exporter_config

- name: Create texfile collector dir
  when: otus_node_exporter_textfile_dir | length > 0
  file:
    path: "{{ otus_node_exporter_textfile_dir }}"
    state: directory
    owner: "{{ otus_node_exporter_user_configuration.username }}"
    group: "{{ otus_node_exporter_user_configuration.group }}"
    recurse: true
    mode: 0775

- name: Allow Node Exporter port in SELinux on RedHat OS family
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"
  seport:
    ports: "{{ otus_node_exporter_web_listen_address.split(':')[1] }}"
    proto: tcp
    setype: http_port_t
    state: present
