---
- name: Install dependencies
  package:
    name: "{{ otus_node_exporter_dependencies }}"
    state: present

- name: Ensure group exist
  group:
    name: "{{ otus_node_exporter_user_configuration.group }}"
    system: "{{ otus_node_exporter_user_configuration.system | default(omit) }}"
    gid: "{{ otus_node_exporter_user_configuration.gid | default(omit) }}"

- name: Ensure user exist
  user:
    name: "{{ otus_node_exporter_user_configuration.username }}"
    password: "{{ otus_node_exporter_user_configuration.password | default(omit) }}"
    system: "{{ otus_node_exporter_user_configuration.system  | default(omit)}}"
    uid: "{{ otus_node_exporter_user_configuration.uid | default(omit) }}"
    shell: "{{ otus_node_exporter_user_configuration.shell | default(omit) }}"
    home: "{{ otus_node_exporter_user_configuration.home | default(omit) }}"
    create_home: "{{ otus_node_exporter_user_configuration.create_home | default(omit) }}"
  no_log: "{{ otus_node_exporter_no_log | default(omit) }}"

#- name: Ensure directories for node_exporter exist with right permissions
#  file:
#    path: "{{ item }}"
#    mode: "{{ otus_node_exporter_data_dir_mode }}"
#    owner: "{{ otus_node_exporter_user_configuration.username }}"
#    group: "{{ otus_node_exporter_user_configuration.group }}"
#    state: directory
#  loop:
#    - "{{ otus_node_exporter_data_dir }}"

##note: To handle destination directory where node_exporter is supposed to be installed
# create directory for the node_exporter and then extract components there because of:
# - 'unarchived' task does not create destination directory
# - node_exporter archive contains directory
- name: Check node_exporter is installed
  file:
    path: "{{ otus_node_exporter_path }}"
    mode: "{{ otus_node_exporter_path_mode }}"
    owner: "{{ otus_node_exporter_user_configuration.username }}"
    group: "{{ otus_node_exporter_user_configuration.group }}"
    state: directory
  register: __otus_node_exporter_installed

- name: Unarchive node_exporter distribution
  when: __otus_node_exporter_installed.changed
  unarchive:
    src: "{{ otus_node_exporter_archive_path }}"
    dest: "{{ otus_node_exporter_path }}"
    owner: "{{ otus_node_exporter_user_configuration.username }}"
    group: "{{ otus_node_exporter_user_configuration.group }}"
    remote_src: true
    extra_opts: [--strip-components=1]  ##note: extract from internal directory at level 1
#  no_log: "{{ otus_node_exporter_no_log }}"

- name: "Ensure node_exporter scripts are in '{{ otus_node_exporter_bin_dir }}'"
  file:
    path: "{{ otus_node_exporter_bin_dir }}/{{ item }}"
    src: "{{ otus_node_exporter_path }}/{{ item }}"
    state: link
  loop:
    - node_exporter
