---
- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution_file_variety | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"

- include_tasks: preflight.yml

- import_tasks: "install-{{ otus_node_exporter_install_method }}.yml"
  become: true

- import_tasks: configure.yml
  become: true

- import_tasks: state.yml
  become: true
