---
- name: Install SELinux dependencies
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"
  become: true
  package:
    name: "{{ otus_prometheus_selinux_packages }}"
    state: present

- name: Allow Node Exporter port in SELinux on RedHat OS family
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"
  seport:
    ports: "{{ node_exporter_web_listen_address.split(':')[1] }}"
    proto: tcp
    setype: http_port_t
    state: present
